### ISSUE TITLE
misleading documentation

### ISSUE THREAD

**Issue by ro70** [senecajs/seneca-mysql-store#30]
Under 'usage -> query support' you write (among other examples)

`.list$({f1:v1, ...}, {sort$:{field1:1}})`

That format doesn't work for me. Instead I have to use

`.list$({f1:v1, ..., sort$:{field1:1}})`

**Comment by mcdonnelldean** [comment]
@ro70 Good spot. @mihaidma @geek This is something that needs to change in a few place. Including the docs if it is wrong.

**Comment by mihaidma** [comment]
I'll check this

**Comment by mihaidma** [comment]
Moved to seneca-standard-query: https://github.com/senecajs-labs/seneca-standard-query/issues/8
